baseURL = "https://mudeteinvestment.netlify.app"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Mudete Investment"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [Mudete Investment Limited](https://mudeteinvestment.netlify.app) All Rights Reserved"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.footer]]
URL = "about"
name = "About"
weight = 1
[[Languages.en.menu.footer]]
URL = "project"
name = "Project"
weight = 2
[[Languages.en.menu.footer]]
URL = "faq"
name = "FAQ"
weight = 5
[[Languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[Languages.en.menu.main]]
URL = "/"
name = "Home"
weight = 1
[[Languages.en.menu.main]]
URL = "about"
name = "About"
weight = 2
[[Languages.en.menu.main]]
URL = "project"
name = "Project"
weight = 3
[[Languages.en.menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[[Languages.en.menu.main]]
URL = "faq"
name = "FAQ"
parent = "Pages"
[[Languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 7
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 [Mudete Investment Limited](https://mudeteinvestment.netlify.app) All Rights Reserved"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[Languages.fr.menu.footer]]
URL = "about"
name = "About"
weight = 1
[[Languages.fr.menu.footer]]
URL = "project"
name = "Project"
weight = 2
[[Languages.fr.menu.footer]]
URL = "service"
name = "Service"
weight = 3
[[Languages.fr.menu.footer]]
URL = "pricing"
name = "Pricing"
weight = 4
[[Languages.fr.menu.footer]]
URL = "faq"
name = "FAQ"
weight = 5
[[Languages.fr.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[Languages.fr.menu.main]]
URL = "/"
name = "Accueil"
weight = 1
[[Languages.fr.menu.main]]
URL = "about"
name = "À propos"
weight = 2
[[Languages.fr.menu.main]]
URL = "project"
name = "Projet"
weight = 3
[[Languages.fr.menu.main]]
URL = "service"
name = "Un service"
weight = 4
[[Languages.fr.menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[[Languages.fr.menu.main]]
hasChildren = true
name = "Pages"
weight = 6
[[Languages.fr.menu.main]]
URL = "faq"
name = "FAQ"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "pricing"
name = "Tarification"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "contact"
name = "Contact"
weight = 7
[params]
author = "Stephen Ajulu"
contact_form_action = "#"
description = "Mudete Investment is an indigenous Kenyan owned mineral exploration and mining company which began operations in late 2019. The company was founded by Kenyans with a passion in mineral exploration. It has since been exploring in Kakamega and Kisumu for gold (Au) and other precious minerals."
email = "mudeteinv@gmail.com"
google_analitycs_id = ""
location = "Nairobi, Kenya"
logo = "images/logo.png"
mobile = "0726024210"
multi_author = false
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Contact Us"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = false
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-googleplus-outline"
link = "#"
